### ISSUE TITLE
PBLimiter does nothing

### ISSUE THREAD

**Issue by Sigurdovich** [sirhamsteralot/HaE-PBLimiter#31] opened 2020-04-21 02:05 UTC
Hello there,

Seems plugin does nothing
!pblimiter status return empty window

![pblimiter](https://user-images.githubusercontent.com/3630729/79814580-4cc4a200-8387-11ea-905f-095b1400d9a0.PNG)

**Comment by azazar** [comment] 2020-04-22 18:29
Are you sure that you have PBs running at that moment?

**Comment by Sigurdovich** [comment] 2020-04-22 19:40
Torch say plugin loaded
How can i check plugin running or not? My server place on hosting pingperfect.com and i have no GUI for dedicated server and Torch

PBs running

![plugin3](https://user-images.githubusercontent.com/3630729/80026729-49e2c200-84eb-11ea-90d9-4cd10e0ff20a.PNG)

![plugin2](https://user-images.githubusercontent.com/3630729/80026065-308d4600-84ea-11ea-94f0-bf0160f0ad37.PNG)

![plugins](https://user-images.githubusercontent.com/3630729/80025287-0dae6200-84e9-11ea-8ae0-ed5c97b3ac2b.PNG)

**Comment by azazar** [comment] 2020-05-03 07:24
`!pblimiter status` displays stats for only PBs owned by local player and which have been executing scripts within configured timeout. It's not displaying just all PBs that the server is running. To check if it's running setup PB with script that won't fit within allowed exection time. Something like that:

```cs
Program()
{
    Runtime.UpdateFrequency = UpdateFrequency.Update1;
}

void Main() {
    for(int i = 0; i < 500; i++)
    {
        Me.CustomData = "" + i;
    }
}
```

**Comment by klemens-st** [comment] 2020-05-11 08:51
I have the exact same problem. The plugin doesn't work on a server without GUI. I tested same save file both on a server with and without GUI.

@azazar On a no GUI server with PBLimiter loaded the script you posted broke the server, the plugin didn't stop it.

**Comment by sirhamsteralot** [comment] 2020-05-11 19:44
that makes absolutely no sense why it wouldnt work, ill have to look into it none of the actual logic of the plugin is tied to the UI sooo....

**Comment by klemens-st** [comment] 2020-05-12 07:16
A bit more information: at first I thought it might be a problem with the rented server I'm using but I've just launched Torch locally with `<NoGui>true</NoGui>` and the problem is exactly the same.

**Comment by sirhamsteralot** [comment] 2020-05-12 21:48
can i see your full config for pblimiter?

**Comment by klemens-st** [comment] 2020-05-12 21:58
```xml
<?xml version="1.0" encoding="utf-8"?>
<ProfilerConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <SerializeWrapTicks>20</SerializeWrapTicks>
  <SerializeWrapViolationsMult>0.1</SerializeWrapViolationsMult>
  <SerializeWrapTime>0.2</SerializeWrapTime>
  <SerializeWrapTimeOutTime>300</SerializeWrapTimeOutTime>
  <SerializeWrapSignificance>0.005</SerializeWrapSignificance>
  <SerializeWrapPerPlayer>true</SerializeWrapPerPlayer>
  <SerializeWrapAllowCleanup>true</SerializeWrapAllowCleanup>
  <SerializeWrapPlayerOverrides>
    <Player>
      <Name>zymeth</Name>
      <SteamId>0</SteamId>
      <PersonalMaxMs>10</PersonalMaxMs>
      <OverrideEnabled>true</OverrideEnabled>
    </Player>
  </SerializeWrapPlayerOverrides>
  <TakeIngameMeasurement>true</TakeIngameMeasurement>
</ProfilerConfig>
```

**Comment by klemens-st** [comment] 2020-05-12 22:02
It works fine with GUI enabled.

**Comment by Tobiti** [comment] 2021-02-26 15:42
I have the same problem

**Comment by Tobiti** [comment] 2021-03-02 09:49
I found the problem
In PBData.cd line 37 you check for UserControl and its null so you just return. 
So instead of just returning, add the date too

**Comment by klemens-st** [comment] 2021-03-03 19:44
Well spotted, I remember looking through the code back then but I missed this one.

**Comment by sirhamsteralot** [comment] 2024-10-17 09:52
Thanks for the chats guys, i will have a look at implementing it in the next round of fixes! (yes i know this is like 3 years later but im getting back in the game now)

**Comment by sirhamsteralot** [comment] 2024-10-17 18:41
Resolved in 2024-1 upstream. you can find the fix in the next release!

**Closed as completed by sirhamsteralot** 2024-10-17 18:41 UTC
Labels: bug
